#!/bin/bash
# setup_protos.sh -- one-shot bootstrap that extracts the pre-generated
# NRE gRPC Python stubs (`*_pb2.py`, `*_pb2_grpc.py`) from the cached
# NRE Docker image into a host-side dir that thin_client.py can import.
#
# Idempotent: if the cache already matches the current image SHA, exits 0
# without re-extracting. The cache-hit path is one `docker image inspect`
# call + a file read + a string compare, so it's safe to invoke before
# every render; actual latency depends on the local docker daemon.
#
# Why extract instead of recompile from `.proto`:
#   The `_pb2.py` files inside the image were generated by the NRE build
#   against its own `.proto` schema with the same protobuf library
#   version the server uses. Extracting them is strictly simpler --
#   no grpc_tools.protoc, no pip dep, no toolchain skew. If the proto
#   schema changes upstream, the new image SHA invalidates this cache
#   and the next call regenerates from the new image.
#
# Usage:
#   bash setup_protos.sh                      # use defaults
#   bash setup_protos.sh --image <tag>        # override image
#   bash setup_protos.sh --out <dir>          # override output dir
#   bash setup_protos.sh --force              # re-extract even if cached
#
# Env overrides:
#   NRE_IMAGE                    default: first locally-cached NRE
#                                renderer image (matches `/nre[-_:]`
#                                paths, excludes `tools` / `isaac`
#                                siblings). Override to pin a specific
#                                tag.
#   NRE_RENDER_CLIENT_PROTO_DIR  default: ~/.cache/nre-render-client/proto
#   NRE_RENDER_CLIENT_PYTHON     default: `python3` on PATH. Set this
#                                to a venv interpreter that already has
#                                grpcio + protobuf + numpy + scipy
#                                installed. Some hosting environments
#                                (launchables, etc.) pre-bake a venv at
#                                /opt/launchable-grpc-py/venv/bin/python3
#                                -- the script falls back to that path
#                                when both NRE_RENDER_CLIENT_PYTHON is
#                                unset and that path exists, before
#                                falling back to `python3` on PATH.

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults + arg parse
# ---------------------------------------------------------------------------
# Image discovery, in order:
#   1. --image flag (set later in the arg-parse loop).
#   2. $NRE_IMAGE env var.
#   3. The image of the running warm-server container (via the state
#      file at /tmp/nre-grpc-session.state -- written by
#      ../../../scripts/session_warm_server.sh on a successful boot).
#      Preferring this guarantees the extracted stubs match the
#      schema of the server the thin client is about to talk to, even
#      when the host has multiple NRE images cached at different
#      versions.
#   4. Highest-versioned locally-cached NRE renderer image (any path
#      matching `*/nre[-_:]*`, excluding the tools/isaac siblings).
IMAGE="${NRE_IMAGE:-}"
if [[ -z "$IMAGE" ]] && [[ -f /tmp/nre-grpc-session.state ]]; then
    _warm_cid="$(awk '{print $1}' /tmp/nre-grpc-session.state 2>/dev/null || true)"
    if [[ -n "$_warm_cid" ]]; then
        IMAGE="$(docker inspect --format '{{.Config.Image}}' "$_warm_cid" 2>/dev/null || true)"
    fi
    unset _warm_cid
fi
if [[ -z "$IMAGE" ]] && command -v docker >/dev/null 2>&1; then
    # Prefer the highest-versioned cached NRE renderer (tag-based sort,
    # no docker run --version overhead). Tags without a parseable
    # X.Y[.Z] sort last so a pinned ":X.Y.Z-<sha>" beats ":latest".
    IMAGE="$(docker images --format '{{.Repository}}:{{.Tag}}' \
        | grep -E '/nre[-_:]' | grep -v -E 'tools|isaac|<none>' \
        | while read -r line; do
            tag="${line##*:}"
            v="$(printf '%s' "$tag" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1)"
            printf '%s\t%s\n' "${v:-0.0.0}" "$line"
          done \
        | sort -V -r | head -1 | cut -f2)"
fi
OUT_DIR="${NRE_RENDER_CLIENT_PROTO_DIR:-${HOME}/.cache/nre-render-client/proto}"
FORCE=0

usage() {
    cat <<USAGE
Usage: setup_protos.sh [options]

  --image TAG    Docker image to extract gRPC stubs from
                 (default: \$NRE_IMAGE, or auto-discovered from cached
                  NRE renderer images on the host)
  --out DIR      Output directory for extracted stubs
                 (default: \$NRE_RENDER_CLIENT_PROTO_DIR or ~/.cache/nre-render-client/proto)
  --force        Re-extract even if cached stubs match the current image SHA
  -h, --help     Show this help
USAGE
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --image) IMAGE="$2";   shift 2 ;;
        --out)   OUT_DIR="$2"; shift 2 ;;
        --force) FORCE=1;      shift   ;;
        -h|--help) usage ;;
        *) echo "unknown flag: $1" >&2; usage ;;
    esac
done

# ---------------------------------------------------------------------------
# Resolve image SHA. If image isn't pulled, instruct + exit.
# ---------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    echo "STOP [setup_protos]: docker not found on PATH." >&2
    exit 1
fi

if [[ -z "$IMAGE" ]]; then
    echo "STOP [setup_protos]: no NRE renderer image found." >&2
    echo "  Auto-discovery looked for cached images matching '/nre[-_:]'" >&2
    echo "  excluding tools / isaac siblings, and found nothing." >&2
    echo "  Pass --image <tag> or set \$NRE_IMAGE." >&2
    exit 1
fi

IMAGE_ID="$(docker image inspect --format '{{.Id}}' "$IMAGE" 2>/dev/null || true)"
if [[ -z "$IMAGE_ID" ]]; then
    echo "STOP [setup_protos]: image '$IMAGE' not present locally." >&2
    echo "  Pull first:  docker pull $IMAGE" >&2
    exit 1
fi
SHA_SHORT="${IMAGE_ID#sha256:}"
SHA_SHORT="${SHA_SHORT:0:12}"

mkdir -p "$OUT_DIR"
SHA_FILE="${OUT_DIR}/.image_sha"
SENTINEL="${OUT_DIR}/nre/grpc/protos/sensorsim_pb2.py"

if [[ "$FORCE" -eq 0 && -f "$SHA_FILE" && -f "$SENTINEL" ]]; then
    if [[ "$(cat "$SHA_FILE")" == "$SHA_SHORT" ]]; then
        echo "[setup_protos] cache hit: image=$IMAGE sha=$SHA_SHORT  (out=$OUT_DIR)"
        exit 0
    fi
fi

echo "[setup_protos] image=$IMAGE  sha=$SHA_SHORT  out=$OUT_DIR  (regenerating)"

# ---------------------------------------------------------------------------
# Locate the stubs inside the image
# ---------------------------------------------------------------------------
CID=""
cleanup() { [[ -n "$CID" ]] && docker rm -f "$CID" >/dev/null 2>&1 || true; }
trap cleanup EXIT

CID="$(docker create --entrypoint /bin/sh "$IMAGE")"

# Probe known paths first (fast). Add more here as NRE release builds move things.
# Layouts seen in the wild:
#   - 26.04 RC `nre_run` (Bazel pycena_run runfiles): /app/run.runfiles/_main/nre/grpc/protos
#   - public 26.04 (flat install):                    /app/nre/grpc/protos
#   - hand-baked images (pip-installed wheel):        /usr/local/lib/python3.{10,11,12}/site-packages/nre/grpc/protos
#   - other:                                          /opt/nre/nre/grpc/protos, /workspace/nre/grpc/protos
KNOWN_PB2_PATHS=(
    "/app/run.runfiles/_main/nre/grpc/protos"
    "/app/nre/grpc/protos"
    "/opt/nre/nre/grpc/protos"
    "/usr/local/lib/python3.10/site-packages/nre/grpc/protos"
    "/usr/local/lib/python3.11/site-packages/nre/grpc/protos"
    "/usr/local/lib/python3.12/site-packages/nre/grpc/protos"
    "/workspace/nre/grpc/protos"
)
PB2_DIR_IN_IMAGE=""
for p in "${KNOWN_PB2_PATHS[@]}"; do
    if docker cp -L "$CID:$p/sensorsim_pb2.py" /dev/null 2>/dev/null; then
        PB2_DIR_IN_IMAGE="$p"
        echo "[setup_protos] stubs found at: $PB2_DIR_IN_IMAGE  (known path)"
        break
    fi
done

# Fallback to a `find` inside the image if no known path matched. Slower (one
# extra container start) but robust to image layout changes.
if [[ -z "$PB2_DIR_IN_IMAGE" ]]; then
    echo "[setup_protos] known paths missed; running 'find' inside the image..."
    FOUND="$(docker run --rm --entrypoint /bin/sh "$IMAGE" -c \
        'find / -path /proc -prune -o -name sensorsim_pb2.py -print 2>/dev/null' \
        | head -1 || true)"
    if [[ -n "$FOUND" ]]; then
        PB2_DIR_IN_IMAGE="$(dirname "$FOUND")"
        echo "[setup_protos] stubs found at: $PB2_DIR_IN_IMAGE  (find fallback)"
    fi
fi

if [[ -z "$PB2_DIR_IN_IMAGE" ]]; then
    echo "STOP [setup_protos]: sensorsim_pb2.py not found in image $IMAGE" >&2
    echo "  This script expects the NRE Python package (nre/grpc/protos/) inside the image." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Extract + Python package scaffolding + sanity check
# ---------------------------------------------------------------------------
rm -rf "${OUT_DIR}/nre"
mkdir -p "${OUT_DIR}/nre/grpc/protos"

for f in common_pb2.py common_pb2_grpc.py sensorsim_pb2.py sensorsim_pb2_grpc.py; do
    if ! docker cp -L "$CID:${PB2_DIR_IN_IMAGE}/${f}" "${OUT_DIR}/nre/grpc/protos/${f}"; then
        echo "STOP [setup_protos]: missing ${f} at ${PB2_DIR_IN_IMAGE} in image $IMAGE" >&2
        exit 1
    fi
done

# __init__.py at every package level so Python imports cleanly.
touch "${OUT_DIR}/nre/__init__.py" \
      "${OUT_DIR}/nre/grpc/__init__.py" \
      "${OUT_DIR}/nre/grpc/protos/__init__.py"

# Resolve the Python interpreter to run the import sanity check under.
# Order of preference:
#   1. $NRE_RENDER_CLIENT_PYTHON (explicit override).
#   2. /opt/launchable-grpc-py/venv/bin/python3 if present (launchable
#      hosting convention).
#   3. `python3` on PATH (developer workstations).
# The selected interpreter MUST have grpcio + protobuf installed; the
# sanity check below verifies that by attempting the imports.
LAUNCHABLE_VENV_PY="/opt/launchable-grpc-py/venv/bin/python3"
if [[ -n "${NRE_RENDER_CLIENT_PYTHON:-}" ]]; then
    SANITY_PY="$NRE_RENDER_CLIENT_PYTHON"
elif [[ -x "$LAUNCHABLE_VENV_PY" ]]; then
    SANITY_PY="$LAUNCHABLE_VENV_PY"
elif command -v python3 >/dev/null 2>&1; then
    SANITY_PY="$(command -v python3)"
else
    echo "STOP [setup_protos]: no python3 available for import sanity check." >&2
    echo "  Set NRE_RENDER_CLIENT_PYTHON to a venv interpreter with grpcio + protobuf." >&2
    exit 1
fi
if [[ ! -x "$SANITY_PY" ]]; then
    echo "STOP [setup_protos]: '$SANITY_PY' is not executable." >&2
    exit 1
fi

if ! "$SANITY_PY" -c "
import sys; sys.path.insert(0, '$OUT_DIR')
from nre.grpc.protos import common_pb2, sensorsim_pb2, sensorsim_pb2_grpc
assert hasattr(common_pb2, 'Pose'), 'common_pb2 missing Pose'
assert hasattr(sensorsim_pb2, 'RGBRenderRequest'), 'sensorsim_pb2 missing RGBRenderRequest'
assert hasattr(sensorsim_pb2, 'BatchRGBRenderRequest'), 'sensorsim_pb2 missing BatchRGBRenderRequest'
print('[setup_protos] import sanity check passed (python=$SANITY_PY)')
"; then
    echo "STOP [setup_protos]: import sanity check failed; stubs at $OUT_DIR are unusable." >&2
    echo "  Sanity check ran under: $SANITY_PY" >&2
    echo "  If you see ModuleNotFoundError for 'google' or 'grpc', that python" >&2
    echo "  doesn't have the thin-client deps. Install them via:" >&2
    echo "      python3 -m venv ~/.venvs/nre-render-client" >&2
    echo "      ~/.venvs/nre-render-client/bin/pip install grpcio protobuf numpy scipy" >&2
    echo "      export NRE_RENDER_CLIENT_PYTHON=~/.venvs/nre-render-client/bin/python3" >&2
    echo "  ...and re-run this script." >&2
    exit 1
fi

echo "$SHA_SHORT" > "$SHA_FILE"
echo "[setup_protos] DONE  image_sha=$SHA_SHORT"
echo "[setup_protos]   stubs:  $OUT_DIR/nre/grpc/protos/{common,sensorsim}_pb2{,_grpc}.py"
echo "[setup_protos]   thin_client.py picks them up automatically (default cache dir)."
